### ISSUE TITLE
Update Arachne and Atlas to latest versions

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/ARACHNE#8]
Can we make sure we are in sync with OHDSI on our servers?

Atlas current is 2.7.4

Arachne current is unknown to me since i am not able to create an account on arachne.ohdsi.org to check. I did think you mentioned a new version was released @gklebanov?

**Comment by gklebanov** [comment]
@PRijnbeek EHDEN is already on an update schedule. For EHDEN, we maintain both ATLAS and ARACHNE. The ATLAS is up to the latest 2.7.4 (was released just a few days ago). The lates ARACHNE release 1.15 was finalized a couple of days ago and will be pushed into prod next week. @konstjar  - could you please provide an exact date?

@PRijnbeek  - what problem do you see when trying to use the OHDSI insance? Could you please share some details offline so that we look into what is happening? Thanks

**Comment by PRijnbeek** [comment]
Hi @gklebanov Atlas on test-atlas.ehden.eu is not at 2.7.4

<img width="253" alt="image" src="https://user-images.githubusercontent.com/7252105/66715337-7e4e2680-edc2-11e9-8722-2efec953f4be.png">

What is the update schedule exactly?

There are two issues with arachne.ohdsi.org:

1. The certificate is not correct therefore No Secure connection can be made
2. The confirmation email returns an error:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/7252105/66715383-fcaac880-edc2-11e9-8ead-380c8d1ea9e2.png">

**Comment by gklebanov** [comment]
aha, I misread your "Atlas current is 2.7.4" as it is the EHDEN ATLAS deployed.

The update idea is the following:
1) For each major release, target to upgrade all customers within 2-3 weeks time period
2) For a patch release, upgrade affected customers first. Keep in mind that 2.7.4 is a maintenance build. Meaning there is no new features but bug fixes. These bug fixes might not be even applicable to specific sites - like Impala or Google BigQuery for EHDEN test, for example. In these cases, we might even skip deploying a maintenance build.

ALAS 2.7.4 was officially released ~ week ago. ARACHNE 1.15 (the latest) - just a couple of days ago. I will let @konstjar provide a specific update schedule and if there is even a need to deploy ATLAS 2.7.4 into EHDEN

Thanks for OHDSI ARACHNE info - I will forward it to our support team to see what is going on with confirmation emails. the SSL certificate was never provided from the start but definitely a good idea to deploy ASAP.
